# Generated by Django 3.0 on 2024-10-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sub',
            name='status',
        ),
    ]
