
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
path('login/',views.login),
path('login_post/',views.login_post),
path('admin_change_passw/',views.change_password),
path('admin_change_passw_post/',views.change_password_post),
path('admin_home/',views.admin_home),
path('admin_add_category/',views.admin_add_category),
path('admin_add_category_post/',views.admin_add_category_post),
path('admin_view_category/',views.admin_view_category),
path('admin_edit_category/<id>',views.admin_edit_category),
path('admin_edit_category_post/',views.admin_edit_category_post),
path('admin_delete_category/<id>',views.admin_delete_category),
path('admin_viewfarmers_products/',views.admin_viewfarmers_products),
path('admin_viewproducts_order/<id>',views.admin_viewproducts_order),
path('admin_viewproducts_order_post/',views.admin_viewproducts_order_post),
path('admin_order/<id>',views.admin_order),
path('admin_order_post/',views.admin_order_post),
path('admin_purchase_main/',views.admin_purchase_main),
path('admin_purchase_sub/<id>',views.admin_purchase_sub),
path('admin_addstock/',views.admin_addstock),
path('admin_add_stock_post/',views.admin_add_stock_post),
path('admin_viewstock/',views.admin_viewstock),
path('admin_viewstock_post/',views.admin_viewstock_post),
path('admin_editstock/<id>',views.admin_editstock),
path('admin_edit_stock_post/',views.admin_editstock_post),
path('admin_delete_stock/<id>',views.admin_delete_stock),
path('admin_send_notification/',views.admin_send_notification),
path('admin_send_notification_post/',views.admin_send_notification_post),
path('admin_view_user_order/',views.admin_view_user_order),
path('admin_order_main/',views.admin_order_main),
path('admin_order_sub/<id>',views.admin_order_sub),
path('admin_view_complaints/',views.admin_view_complaints),
path('admin_view_complaints_post/',views.admin_view_complaints_post),
path('admin_view_payment/',views.admin_view_payment),
path('admin_send_reply/<id>',views.admin_send_reply),
path('admin_send_reply_post/',views.admin_send_reply_post),
path('admin_view_feedback/',views.admin_view_feedback),
path('admin_view_feedback_post/',views.admin_view_feedback_post),
path('payment1/<amount>',views.raz_pay1),


path('farmer_home/',views.farmer_home),
path('farmer_change_password/',views.farmer_change_password),
path('farmer_change_passw_post/',views.farmer_change_password_post),
path('farmer_registration/',views.farmer_registration),
path('farmer_registration_post/',views.farmer_registration_post),
path('farmer_view_profile/',views.farmer_view_profile),
path('farmer_update_profile/',views.farmer_update_profile),
path('farmer_update_profile_post/',views.farmer_update_profile_post),
path('farmer_add_product/',views.farmer_add_product),
path('farmer_add_product_post/',views.farmer_add_product_post),
path('farmer_view_product/',views.farmer_view_product),
path('farmer_view_product_post/',views.farmer_view_product_post),
path('farmer_edit_product/<id>',views.farmer_edit_product),
path('farmer_edit_product_post/',views.farmer_edit_product_post),
path('farmer_delete_product/<id>',views.farmer_delete_product),
path('farmer_view_notification/',views.farmer_view_notifications),
path('farmer_view_payment/',views.farmer_view_payment),
path('farmer_view_order/',views.farmer_view_order),
path('farmer_view_approved_order/',views.farmer_view_approved_order),
path('farmer_view_more/<id>',views.farmer_view_more),
path('farmer_approve_order/<id>',views.farmer_approve_order),
path('farmer_reject_order/<id>',views.farmer_reject_order),

path('user_home/',views.userhome),
path('user_change_passw/',views.user_change_password),
path('user_change_passw_post/',views.user_change_passw_post),
path('user_registration/',views.user_registration),
path('user_registration_post/',views.user_registration_post),
path('user_view_profile/',views.user_view_profile),
path('user_view_product/',views.user_view_product),
path('user_view_product_post/',views.user_view_product_post),
path('user_add_productto_cart/<id>',views.user_add_productto_cart),
path('user_add_productto_cart_post/',views.user_add_productto_cart_post),
path('user_view_cart/',views.user_view_cart),
path('user_remove_cart/<id>',views.user_remove_cart),
path('user_send_complaints/',views.user_send_complaints),
path('user_send_complaints_post/',views.user_send_complaints_post),
path('user_view_reply/',views.user_view_reply),
path('user_send_feedback/',views.user_send_feedback),
path('user_send_feedback_post/',views.user_send_feedback_post),
path('payment/<amount>',views.raz_pay),

]
